[package]
name = "simple_logger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ezlog = { path = "../../ezlog-core", features = ["log"]}
log = "0.4.0"
env_logger = "0.10.0"
dirs = "5.0"