name: Install mdbook and dependencies

description: Install mdbook with the dependencies we need.

runs:
  using: composite
  steps:
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    # The --locked flag is important for reproducible builds. It also
    # avoids breakage due to skews between mdbook and mdbook-svgbob.
    - name: Install mdbook
      run: cargo install mdbook --locked --version 0.4.35
      shell: bash

    - name: Install mdbook-svgbob
      run: cargo install mdbook-svgbob --git https://github.com/boozook/mdbook-svgbob --rev 6f62155
      shell: bash

    - name: Install mdbook-i18n-helpers
      run: cargo install mdbook-i18n-helpers --locked --version 0.2.4
      shell: bash