# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  platform :ios, '14.0'

end

target 'EZLog' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  platform :ios, '13.0'

end

target 'benchmark' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  platform :ios, '12.0'

  # Pods for benchmark
  
  pod 'Logan', '~> 1.2.9'

end

target 'benchmarkable' do
  use_frameworks!

  platform :ios, '12.0'

  # Pods for benchmark
end
