name: 'Setup Android Environment'
description: 'Setup Android SDK, NDK and Java for building Android apps'

inputs:
  ndk-version:
    description: 'NDK version to install'
    default: '27.0.11902837'
    required: false
  build-tools-version:
    description: 'Build tools version'
    default: '34.0.0'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      id: android-sdk
      with:
        packages: platforms;android-34 build-tools;${{ inputs.build-tools-version }} platform-tools ndk;${{ inputs.ndk-version }}
        
    - name: Set Android environment variables
      shell: bash
      run: |
        if [ ! -d "$ANDROID_HOME" ]; then
          echo "Android SDK not found at $ANDROID_HOME"
          exit 1
        fi
        
        NDK_PATH="$ANDROID_HOME/ndk/${{ inputs.ndk-version }}"
        echo "NDK_HOME=$NDK_PATH" >> $GITHUB_ENV

        echo "$ANDROID_HOME/build-tools/${{ inputs.build-tools-version }}" >> $GITHUB_PATH
        echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
        echo "$NDK_PATH" >> $GITHUB_PATH

    - name: Add Rust Android targets
      shell: bash
      run: |
        rustup target add aarch64-linux-android
        rustup target add armv7-linux-androideabi
        rustup target add i686-linux-android
        rustup target add x86_64-linux-android

    - name: Validate environment
      shell: bash
      run: |
        echo "=== Environment Validation ==="
        echo "Java: $(java -version 2>&1 | head -n 1)"
        echo "NDK: $NDK_HOME (exists: $(test -d "$NDK_HOME" && echo 'YES' || echo 'NO'))"
        echo "Rust targets: $(rustup target list | grep android | tr '\n' ' ')"