# .github/workflows/publish.yml
name: Publish to pub.dev

on: [workflow_dispatch]

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ezlog_flutter
    steps:
      - uses: actions/checkout@v5
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: flutter pub get
      # Here you can insert custom steps you need
      # - run: dart tool/generate-code.dart
      - name: Publish
        run: flutter pub publish --force
